name: octify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  image_picker: ^1.0.8
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  circular_countdown_timer: ^0.2.3
  flutter_bloc: ^8.1.5
  kiwi: ^5.0.0
  dio: ^5.4.3+1
  quick_log: ^5.3.1
  animate_do: ^3.3.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.3
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.1
  google_sign_in: ^6.2.1
  google_generative_ai: ^0.4.4
  flutter_riverpod: ^2.5.1
  flutter_html: ^3.0.0-alpha.5
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  flutter_markdown: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf