// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWaDdl0In5RKwi1EM3S6rVpUM2PI4EXg4',
    appId: '1:761011857743:android:60745be007517bc4f1fd3a',
    messagingSenderId: '761011857743',
    projectId: 'octifyai',
    databaseURL: 'https://octifyai-default-rtdb.firebaseio.com',
    storageBucket: 'octifyai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJTCigISH3C_oEmrW8UtfQt26KpYBgdo',
    appId: '1:761011857743:ios:f6627dda3e2cf978f1fd3a',
    messagingSenderId: '761011857743',
    projectId: 'octifyai',
    databaseURL: 'https://octifyai-default-rtdb.firebaseio.com',
    storageBucket: 'octifyai.appspot.com',
    androidClientId: '761011857743-ovp0ptr5aus8853v7coe6i66n3ocge40.apps.googleusercontent.com',
    iosClientId: '761011857743-doot3akc0ehmp3vvb6a48b3ofpfjcve3.apps.googleusercontent.com',
    iosBundleId: 'com.araby.octify',
  );

}